"""This module contain data of S&P 500 CEOs full name along with their company name in the tuple."""

corpus = [
    ("@MCMULLEN_73927", "Michael McMullen", "Agilent Technologies Inc."),
    ("@PARKER_52643", "Douglas Parker", "American Airlines Group Inc."),
    ("@ISOM_77122", "Robert Isom", "American Airlines Group Inc."),
    ("@GRECO_90859", "Thomas Greco", "Advance Auto Parts Inc."),
    ("@COOK_49578", "Timothy Cook", "Apple Inc."),
    ("@GONZALEZ_51276", "Richard Gonzalez", "AbbVie Inc."),
    ("@COLLIS_49463", "Steven Collis", "AmerisourceBergen Corp."),
    ("@MINOGUE_54322", "Michael Minogue", "Abiomed Inc."),
    ("@WHITE_49457", "Miles White", "Abbott Laboratories"),
    ("@FORD_170571", "Robert Ford", "Abbott Laboratories"),
    ("@NANTERME_49512", "Pierre Nanterme", "Accenture PLC"),
    ("@ROWLAND_56540", "David Rowland", "Accenture PLC"),
    ("@SWEET_49516", "Julie Sweet", "Accenture PLC"),
    ("@OLLAGNIER_191934", "Jean-Marc Ollagnier", "Accenture PLC"),
    ("@NARAYEN_49505", "Shantanu Narayen", "Adobe Inc."),
    ("@ROCHE_49514", "Vincent Roche", "Analog Devices Inc."),
    ("@LUCIANO_59659", "Juan Luciano", "Archer Daniels Midland Co."),
    ("@RODRIGUEZ_49635", "Carlos Rodriguez", "Automatic Data Processing Inc."),
    ("@ANAGNOST_58739", "Andrew Anagnost", "Autodesk Inc."),
    ("@HANSPAL_86232", "Amarpreet Hanspal", "Autodesk Inc."),
    ("@ANAGNOST_58739", "Andrew Anagnost", "Autodesk Inc."),
    ("@BAXTER_57603", "Warner Baxter", "Ameren Corp."),
    ("@AKINS_49452", "Nicholas Akins", "American Electric Power Co. Inc."),
    ("@GLUSKI_49403", "Andrés Gluski", "The AES Corp."),
    ("@AMOS_49521", "Daniel Amos", "Aflac Inc."),
    ("@HANCOCK_58355", "Peter Hancock", "American International Group Inc."),
    ("@DUPERREAULT_62228", "Brian Duperreault", "American International Group Inc."),
    ("@ZAFFINO_77117", "Peter Zaffino", "American International Group Inc."),
    ("@HOGAN_77208", "Kevin Hogan", "American International Group Inc."),
    ("@ZAFFINO_77117", "Peter Zaffino", "American International Group Inc."),
    ("@COLBERG_58723", "Alan Colberg", "Assurant Inc."),
    ("@LEMASTERS_90645", "Craig Lemasters", "Assurant Inc."),
    ("@MERGELMEYER_77552", "Gene Mergelmeyer", "Assurant Inc."),
    ("@GALLAGHER_54149", "J. Gallagher", "Arthur J. Gallagher & Co."),
    ("@HUDSON_177161", "Scott Hudson", "Arthur J. Gallagher & Co."),
    ("@LEIGHTON_49475", "Thomson Leighton", "Akamai Technologies Inc."),
    ("@KISSAM_50754", "Luther Kissam", "Albemarle Corp."),
    ("@MASTERS_58020", "Kent Masters", "Albemarle Corp."),
    ("@HOGAN_55026", "Joseph Hogan", "Align Technology Inc."),
    ("@TILDEN_54199", "Bradley Tilden", "Alaska Air Group Inc."),
    ("@MINICUCCI_77756", "Benito Minicucci", "Alaska Air Group Inc."),
    ("@CAMPBELL_89893", "David Campbell", "Alaska Air Group Inc."),
    ("@WILSON_62392", "Thomas Wilson", "The Allstate Corp."),
    ("@CIVGIN_49509", "Don Civgin", "The Allstate Corp."),
    ("@PETRATIS_52173", "David Petratis", "Allegion PLC"),
    ("@DICKERSON_56418", "Gary Dickerson", "Applied Materials Inc."),
    ("@DELIA_55164", "Ronald Delia", "Amcor PLC"),
    ("@SU_59364", "Lisa Su", "Advanced Micro Devices Inc."),
    ("@ZAPICO_77392", "David Zapico", "AMETEK Inc."),
    ("@BRADWAY_49494", "Robert Bradway", "Amgen Inc."),
    ("@CRACCHIOLO_49448", "James Cracchiolo", "Ameriprise Financial Inc."),
    ("@TRUSCOTT_77313", "William Truscott", "Ameriprise Financial Inc."),
    ("@TAICLET_49421", "James Taiclet", "American Tower Corp."),
    ("@BARTLETT_49424", "Thomas Bartlett", "American Tower Corp."),
    ("@BEZOS_49416", "Jeffrey Bezos", "Amazon.com Inc."),
    ("@JASSY_49423", "Andrew Jassy", "Amazon.com Inc."),
    ("@WILKE_77152", "Jeffrey Wilke", "Amazon.com Inc."),
    ("@CLARK_196961", "David Clark", "Amazon.com Inc."),
    ("@JASSY_49423", "Andrew Jassy", "Amazon.com Inc."),
    ("@ULLAL_58431", "Jayshree Ullal", "Arista Networks Inc."),
    ("@GOPAL_59792", "Ajei Gopal", "ANSYS Inc."),
    ("@SWEDISH_50598", "Joseph Swedish", "Anthem Inc."),
    ("@BOUDREAUX_61348", "Gail Boudreaux", "Anthem Inc."),
    ("@GRIFFIN_90048", "Brian Griffin", "Anthem Inc."),
    ("@CASE_49577", "Gregory Case", "Aon PLC"),
    ("@SAVACOOL_49606", "Kristi Savacool", "Aon PLC"),
    ("@O'CONNOR_96054", "Michael O'connor", "Aon PLC"),
    ("@RAJENDRA_54417", "Ajita Rajendra", "A. O. Smith Corp."),
    ("@WHEELER_77755", "Kevin Wheeler", "A. O. Smith Corp."),
    ("@CHRISTMANN_67965", "John Christmann", "Apache Corp."),
    ("@GHASEMI_51893", "Seifollah Ghasemi", "Air Products and Chemicals Inc."),
    ("@NORWITT_50772", "Adam Norwitt", "Amphenol Corp."),
    ("@SIMON_52984", "Irwin Simon", "Aphria Inc."),
    ("@CLARK_49996", "Kevin Clark", "Aptiv PLC"),
    ("@RICHARDSON_80359", "Stephen Richardson", "Alexandria Real Estate Equities Inc."),
    ("@MARCUS_54285", "Joel Marcus", "Alexandria Real Estate Equities Inc."),
    ("@COCKLIN_54061", "Kim Cocklin", "Atmos Energy Corp."),
    ("@HAEFNER_77782", "Michael Haefner", "Atmos Energy Corp."),
    ("@AKERS_167917", "John Akers", "Atmos Energy Corp."),
    ("@MORHAIME_77821", "Michael Morhaime", "Activision Blizzard Inc."),
    ("@KOTICK_54253", "Robert Kotick", "Activision Blizzard Inc."),
    ("@ZACCONI_91037", "Riccardo Zacconi", "Activision Blizzard Inc."),
    ("@NAUGHTON_49532", "Timothy Naughton", "AvalonBay Communities Inc."),
    ("@TAN_54077", "Hock Tan", "Broadcom Inc."),
    ("@BUTIER_49574", "Mitchell Butier", "Avery Dennison Corp."),
    ("@STORY_54160", "Susan Story", "American Water Works Co. Inc."),
    ("@LYNCH_77829", "Walter Lynch", "American Water Works Co. Inc."),
    ("@CHENAULT_51346", "Kenneth Chenault", "American Express Co."),
    ("@SQUERI_77198", "Stephen Squeri", "American Express Co."),
    ("@RHODES_49667", "William Rhodes", "Autozone Inc."),
    ("@MUILENBURG_49640", "Dennis Muilenburg", "The Boeing Co."),
    ("@DEAL_170573", "Stanley Deal", "The Boeing Co."),
    ("@MCALLISTER_89801", "Kevin McAllister", "The Boeing Co."),
    ("@SMITH_49641", "Gregory Smith", "The Boeing Co."),
    ("@CALHOUN_52028", "David Calhoun", "The Boeing Co."),
    ("@MOYNIHAN_49523", "Brian Moynihan", "Bank of America Corp."),
    ("@ALMEIDA_49857", "Jose Almeida", "Baxter International Inc."),
    ("@COE_77187", "Nicholas Coe", "Bath & Body Works Inc."),
    ("@MESLOW_196447", "Andrew Meslow", "Bath & Body Works Inc."),
    ("@WATERS_90159", "Martin Waters", "Bath & Body Works Inc."),
    ("@JOLY_49735", "Hubert Joly", "Best Buy Co. Inc."),
    ("@BARRY_91706", "Corie Barry", "Best Buy Co. Inc."),
    ("@FORLENZA_49691", "Vincent Forlenza", "Becton Dickinson and Co."),
    ("@POLEN_89426", "Thomas Polen", "Becton Dickinson and Co."),
    ("@JOHNSON_49917", "Gregory Johnson", "Franklin Resources Inc."),
    ("@JOHNSON_77098", "Jennifer Johnson", "Franklin Resources Inc."),
    ("@COX_66223", "John Cox", "Biogen Inc."),
    ("@VOUNATSOS_91299", "Michel Vounatsos", "Biogen Inc."),
    ("@SCHWARTZ_54123", "Norman Schwartz", "Bio-Rad Laboratories Inc."),
    ("@EHMER_58879", "Bernhard Ehmer", "Biotest AG"),
    ("@HASSELL_49571", "Gerald Hassell", "Bank of New York Mellon Corp."),
    ("@HARRIS_85845", "Mitchell Harris", "Bank of New York Mellon Corp."),
    ("@SCHARF_50701", "Charles Scharf", "Bank of New York Mellon Corp."),
    ("@GIBBONS_49570", "Thomas Gibbons", "Bank of New York Mellon Corp."),
    ("@GIBBONS_49570", "Thomas Gibbons", "Bank of New York Mellon Corp."),
    ("@GIBBONS_49570", "Thomas Gibbons", "Bank of New York Mellon Corp."),
    ("@SHEA_86429", "Brian Shea", "Bank of New York Mellon Corp."),
    ("@TANS_87481", "Gillian Tans", "Booking Holdings Inc."),
    ("@FOGEL_58764", "Glenn Fogel", "Booking Holdings Inc."),
    ("@SIMONELLI_166450", "Lorenzo Simonelli", "Baker Hughes Co."),
    ("@CHRISTIE_177836", "Roderick Christie", "Baker Hughes Co."),
    ("@FINK_165075", "Laurence Fink", "BlackRock Inc."),
    ("@OBRIEN_51450", "Thomas OBrien", "BlackRock Inc."),
    ("@HAYES_49629", "John Hayes", "Ball Corp."),
    ("@CAFORIO_61326", "Giovanni Caforio", "Bristol-Myers Squibb Co."),
    ("@DALY_54017", "Richard Daly", "Broadridge Financial Solutions Inc."),
    ("@GOKEY_77808", "Timothy Gokey", "Broadridge Financial Solutions Inc."),
    ("@BROWN_53923", "Powell Brown", "Brown & Brown Inc."),
    ("@MAHONEY_49722", "Michael Mahoney", "Boston Scientific Corp."),
    ("@VERRIER_49670", "James Verrier", "BorgWarner Inc."),
    ("@LISSALDE_77299", "Frederic Lissalde", "BorgWarner Inc."),
    ("@THOMAS_49698", "Owen Thomas", "Boston Properties Inc."),
    ("@CORBAT_49742", "Michael Corbat", "Citigroup Inc."),
    ("@FRASER_89762", "Jane Fraser", "Citigroup Inc."),
    ("@BIRD_86463", "Stephen Bird", "Citigroup Inc."),
    ("@FRASER_89762", "Jane Fraser", "Citigroup Inc."),
    ("@FRASER_89762", "Jane Fraser", "Citigroup Inc."),
    ("@FORESE_77105", "James Forese", "Citigroup Inc."),
    ("@CONNOLLY_54664", "Sean Connolly", "Conagra Brands Inc."),
    ("@BARRETT_49643", "George Barrett", "Cardinal Health Inc."),
    ("@KAUFMANN_59242", "Michael Kaufmann", "Cardinal Health Inc."),
    ("@GIACOMIN_88130", "Jon Giacomin", "Cardinal Health Inc."),
    ("@CASEY_77119", "Donald Casey", "Cardinal Health Inc."),
    ("@GIACOMIN_88130", "Jon Giacomin", "Cardinal Health Inc."),
    ("@GITLIN_177230", "David Gitlin", "Carrier Global Corp."),
    ("@UMPLEBY_77029", "James Umpleby", "Caterpillar Inc."),
    ("@GREENBERG_49392", "Evan Greenberg", "Chubb Ltd."),
    ("@TILLY_53804", "Edward Tilly", "Cboe Global Markets Inc."),
    ("@CONCANNON_63810", "William Concannon", "CBRE Group Inc."),
    ("@SULENTIC_49699", "Robert Sulentic", "CBRE Group Inc."),
    ("@FERGUSON_48356", "Ritson Ferguson", "CBRE Group Inc."),
    ("@BROWN_50402", "Jay Brown", "Crown Castle International Corp."),
    ("@LEVENDOS_196122", "Christopher Levendos", "Crown Castle International Corp."),
    ("@THAMM_47954", "Michael Thamm", "Carnival Corp."),
    ("@DONALD_47874", "Arnold Donald", "Carnival PLC"),
    ("@DONALD_47874", "Arnold Donald", "Carnival Corp."),
    ("@KRUSE_47955", "Stein Kruse", "Carnival Corp."),
    ("@THAMM_47954", "Michael Thamm", "Carnival PLC"),
    ("@KRUSE_47955", "Stein Kruse", "Carnival PLC"),
    ("@OSSIP_174635", "David Ossip", "Ceridian HCM Holding Inc."),
    ("@TAN_53957", "Lip-Bu Tan", "Cadence Design Systems Inc."),
    ("@RICHARDS_57030", "Thomas Richards", "CDW Corp."),
    ("@LEAHY_57032", "Christine Leahy", "CDW Corp."),
    ("@ROHR_53989", "Mark Rohr", "Celanese Corp."),
    ("@RYERKERK_86592", "Lori Ryerkerk", "Celanese Corp."),
    ("@SHAFER_177944", "Brent Shafer", "Cerner Corp."),
    ("@PATTERSON_49715", "Neal Patterson", "Cerner Corp."),
    ("@WILLIAMS_56699", "Anthony Williams", "CF Industries Holdings Inc."),
    ("@SAUN_47465", "Bruce Van Saun", "Citizens Financial Group Inc."),
    ("@FARRELL_53906", "Matthew Farrell", "Church & Dwight Co. Inc."),
    ("@WIEHOFF_51456", "John Wiehoff", "C.H. Robinson Worldwide Inc."),
    ("@BIESTERFELD_171535", "Robert Biesterfeld", "C.H. Robinson Worldwide Inc."),
    ("@RUTLEDGE_53771", "Thomas Rutledge", "Charter Communications Inc."),
    ("@CORDANI_49766", "David Cordani", "Cigna Corp."),
    ("@CORDANI_49766", "David Cordani", "Cigna Corp."),
    ("@JOHNSTON_49783", "Steven Johnston", "Cincinnati Financial Corp."),
    ("@COOK_49750", "Ian Cook", "Colgate-Palmolive Co."),
    ("@WALLACE_76982", "Noel Wallace", "Colgate-Palmolive Co."),
    ("@DORER_58637", "Benno Dorer", "The Clorox Co."),
    ("@RENDLE_174028", "Linda Rendle", "The Clorox Co."),
    ("@BABB_49823", "Ralph Babb", "Comerica Inc."),
    ("@FARMER_77359", "Curtis Farmer", "Comerica Inc."),
    ("@ROBERTS_49782", "Brian Roberts", "Comcast Corp."),
    ("@WATSON_67352", "David Watson", "Comcast Corp."),
    ("@BURKE_61757", "Stephen Burke", "Comcast Corp."),
    ("@DUFFY_60758", "Terrence Duffy", "CME Group Inc."),
    ("@NICCOL_87048", "Brian Niccol", "Chipotle Mexican Grill Inc."),
    ("@ELLS_49909", "Steve Ells", "Chipotle Mexican Grill Inc."),
    ("@LINEBARGER_49815", "N. Linebarger", "Cummins Inc."),
    ("@POPPE_77582", "Patricia Poppe", "CMS Energy Corp."),
    ("@ROCHOW_170945", "Garrick Rochow", "CMS Energy Corp."),
    ("@NEIDORFF_55448", "Michael Neidorff", "Centene Corp."),
    ("@PROCHAZKA_56706", "Scott Prochazka", "CenterPoint Energy Inc."),
    ("@SOMERHALDER_49590", "John Somerhalder", "CenterPoint Energy Inc."),
    ("@LESAR_50046", "David Lesar", "CenterPoint Energy Inc."),
    ("@FAIRBANK_49724", "Richard Fairbank", "Capital One Financial Corp."),
    ("@DINGES_49645", "Dan Dinges", "Cabot Oil & Gas Corp."),
    ("@WEISS_53766", "Robert Weiss", "The Cooper Companies Inc."),
    ("@WHITE_58684", "Albert White", "The Cooper Companies Inc."),
    ("@LANCE_49968", "Ryan Lance", "ConocoPhillips"),
    ("@JELINEK_51486", "Craig Jelinek", "Costco Wholesale Corp."),
    ("@MORRISON_49694", "Denise Morrison", "Campbell Soup Co."),
    ("@MCLOUGHLIN_55048", "Keith McLoughlin", "Campbell Soup Co."),
    ("@CLOUSE_90972", "Mark Clouse", "Campbell Soup Co."),
    ("@ADAIR_55640", "A. Adair", "Copart Inc."),
    ("@FOSTER_53602", "James Foster", "Charles River Laboratories International Inc."),
    ("@BENIOFF_50494", "Marc Benioff", "Salesforce.com Inc."),
    ("@BLOCK_61920", "Keith Block", "Salesforce.com Inc."),
    ("@ROBBINS_75039", "Charles Robbins", "Cisco Systems Inc."),
    ("@FOOTE_171162", "James Foote", "CSX Corp."),
    ("@FARMER_49805", "Scott Farmer", "Cintas Corp."),
    ("@SCHNEIDER_180980", "Todd Schneider", "Cintas Corp."),
    ("@CHIMINSKI_58808", "John Chiminski", "Catalent Inc."),
    ("@D'SOUZA_49803", "Francisco D'souza", "Cognizant Technology Solutions Corp."),
    ("@HUMPHRIES_184283", "Brian Humphries", "Cognizant Technology Solutions Corp."),
    ("@COLLINS_86511", "James Collins", "Corteva Inc."),
    ("@TATARINOV_91355", "Kirill Tatarinov", "Citrix Systems Inc."),
    ("@HENSHALL_49767", "David Henshall", "Citrix Systems Inc."),
    ("@MERLO_49834", "Larry Merlo", "CVS Health Corp."),
    ("@LYNCH_80879", "Karen Lynch", "CVS Health Corp."),
    ("@WATSON_49755", "John Watson", "Chevron Corp."),
    ("@WIRTH_77153", "Michael Wirth", "Chevron Corp."),
    ("@CARANO_58659", "Gary Carano", "Caesars Entertainment Inc."),
    ("@FRISSORA_52908", "Mark Frissora", "Caesars Entertainment Corp."),
    ("@REEG_75363", "Thomas Reeg", "Caesars Entertainment Inc."),
    ("@RODIO_138359", "Anthony Rodio", "Caesars Entertainment Corp."),
    ("@FARRELL_49993", "Thomas Farrell", "Dominion Energy Inc."),
    ("@LEOPOLD_171017", "Diane Leopold", "Dominion Energy Inc."),
    ("@BLUE_171029", "Robert Blue", "Dominion Energy Inc."),
    ("@BLUE_171029", "Robert Blue", "Dominion Energy Inc."),
    ("@KOONCE_77069", "Paul Koonce", "Dominion Energy Inc."),
    ("@BASTIAN_61341", "Edward Bastian", "Delta Air Lines Inc."),
    ("@BREEN_60853", "Edward Breen", "DuPont de Nemours Inc."),
    ("@BREEN_60853", "Edward Breen", "E. I. du Pont de Nemours and Co."),
    ("@BREEN_60853", "Edward Breen", "DuPont de Nemours Inc."),
    ("@BREEN_60853", "Edward Breen", "E. I. du Pont de Nemours and Co."),
    ("@DOYLE_86514", "Marc Doyle", "DuPont de Nemours Inc."),
    ("@DOYLE_86514", "Marc Doyle", "E. I. du Pont de Nemours and Co."),
    ("@BREEN_60853", "Edward Breen", "DuPont de Nemours Inc."),
    ("@BREEN_60853", "Edward Breen", "E. I. du Pont de Nemours and Co."),
    ("@ALLEN_49891", "Samuel Allen", "Deere & Co."),
    ("@MAY_89509", "John May", "Deere & Co."),
    ("@NELMS_49894", "David Nelms", "Discover Financial Services"),
    ("@HOCHSCHILD_73943", "Roger Hochschild", "Discover Financial Services"),
    ("@VASOS_75242", "Todd Vasos", "Dollar General Corp."),
    ("@RUSCKOWSKI_50416", "Stephen Rusckowski", "Quest Diagnostics Inc."),
    ("@AULD_59345", "David Auld", "D.R. Horton Inc."),
    ("@JOYCE_58087", "Thomas Joyce", "Danaher Corp."),
    ("@BLAIR_171382", "Rainer Blair", "Danaher Corp."),
    ("@IGER_50638", "Robert Iger", "The Walt Disney Co."),
    ("@IGER_50638", "Robert Iger", "The Walt Disney Co."),
    ("@CHAPEK_192745", "Robert Chapek", "The Walt Disney Co."),
    ("@ZASLAV_51590", "David Zaslav", "Discovery Inc."),
    ("@PERRETTE_77513", "Jean-Briac Perrette", "Discovery Inc."),
    ("@FARICY_177231", "Peter Faricy", "Discovery Inc."),
    ("@ERGEN_64854", "Charles Ergen", "DISH Network Corp."),
    ("@CARLSON_89861", "W. Carlson", "DISH Network Corp."),
    ("@LYNCH_86596", "Roger Lynch", "DISH Network Corp."),
    ("@STEIN_53604", "William Stein", "Digital Realty Trust Inc."),
    ("@SASSER_49972", "Bob Sasser", "Dollar Tree Inc."),
    ("@PHILBIN_79323", "Gary Philbin", "Dollar Tree Inc."),
    ("@WITYNSKI_172643", "Michael Witynski", "Dollar Tree Inc."),
    ("@LIVINGSTON_50012", "Robert Livingston", "Dover Corp."),
    ("@SIVASANKARAN_86687", "Somasundaram Sivasankaran", "Dover Corp."),
    ("@FINCHER_77536", "Anderson Fincher", "Dover Corp."),
    ("@SPURGEON_77576", "William Spurgeon", "Dover Corp."),
    ("@TOBIN_55479", "Richard Tobin", "Dover Corp."),
    ("@LIVERIS_50016", "Andrew Liveris", "The Dow Chemical Co."),
    ("@FITTERLING_63959", "James Fitterling", "The Dow Chemical Co."),
    ("@FITTERLING_63959", "James Fitterling", "Dow Inc."),
    ("@DOYLE_53292", "J. Doyle", "Domino's Pizza Inc."),
    ("@ALLISON_78186", "Richard Allison", "Domino's Pizza Inc."),
    ("@CONNOR_78179", "James Connor", "Duke Realty Corp."),
    ("@LEE_59414", "Eugene Lee", "Darden Restaurants Inc."),
    ("@ANDERSON_50067", "Gerard Anderson", "DTE Energy Co."),
    ("@NORCIA_77338", "Gerardo Norcia", "DTE Energy Co."),
    ("@GOOD_49878", "Lynn Good", "Duke Energy Corp."),
    ("@THIRY_51567", "Kent Thiry", "Davita Inc."),
    ("@RODRIGUEZ_77500", "Javier Rodriguez", "Davita Inc."),
    ("@HAGER_60093", "David Hager", "Devon Energy Corp."),
    ("@LAWRIE_90399", "J. Lawrie", "DXC Technology Co."),
    ("@LAWRIE_90399", "J. Lawrie", "Computer Sciences Corp."),
    ("@LAWRIE_90399", "J. Lawrie", "DXC Technology Co."),
    ("@LAWRIE_90399", "J. Lawrie", "Computer Sciences Corp."),
    ("@SALVINO_185756", "Michael Salvino", "DXC Technology Co."),
    ("@SAYER_57626", "Kevin Sayer", "DexCom Inc."),
    ("@WILSON_47604", "Andrew Wilson", "Electronic Arts Inc."),
    ("@WENIG_75362", "Devin Wenig", "eBay Inc."),
    ("@SCHENKEL_75366", "Scott Schenkel", "eBay Inc."),
    ("@BAKER_49883", "Douglas Baker", "Ecolab Inc."),
    ("@BECK_88171", "Christophe Beck", "Ecolab Inc."),
    ("@MCAVOY_56635", "John McAvoy", "Consolidated Edison Inc."),
    ("@NOYES_196091", "Mark Noyes", "Consolidated Edison Inc."),
    ("@SANCHEZ_178299", "Robert Sanchez", "Consolidated Edison Inc."),
    ("@CAWLEY_86894", "Timothy Cawley", "Consolidated Edison Inc."),
    ("@CAWLEY_86894", "Timothy Cawley", "Consolidated Edison Inc."),
    ("@SMITH_49953", "Richard Smith", "Equifax Inc."),
    ("@BARROS_86312", "Paulino Barros", "Equifax Inc."),
    ("@BEGOR_86551", "Mark Begor", "Equifax Inc."),
    ("@PAYNE_170549", "Kevin Payne", "Edison International"),
    ("@PIZARRO_74986", "Pedro Pizarro", "Edison International"),
    ("@FREDA_47156", "Fabrizio Freda", "Estee Lauder Companies Inc."),
    ("@COSTA_56673", "Mark Costa", "Eastman Chemical Co."),
    ("@FARR_50042", "David Farr", "Emerson Electric Co."),
    ("@KARSANBHAI_182069", "Surendralal Karsanbhai", "Emerson Electric Co."),
    ("@NAHI_55488", "Paul Nahi", "Enphase Energy Inc."),
    ("@GARCIA_88286", "Humberto Garcia", "Enphase Energy Inc."),
    ("@KOTHANDARAMAN_172794", "Badrinarayanan Kothandaraman", "Enphase Energy Inc."),
    ("@THOMAS_55707", "William Thomas", "EOG Resources Inc."),
    ("@SMITH_53474", "Stephen Smith", "Equinix Inc."),
    ("@MEYERS_79043", "Charles Meyers", "Equinix Inc."),
    ("@NEITHERCUT_49961", "David Neithercut", "Equity Residential"),
    ("@PARRELL_49962", "Mark Parrell", "Equity Residential"),
    ("@JUDGE_50335", "James Judge", "Eversource Energy"),
    ("@NOLAN_194894", "Joseph Nolan", "Eversource Energy"),
    ("@SCHALL_53302", "Michael Schall", "Essex Property Trust Inc."),
    ("@ARNOLD_60646", "Craig Arnold", "Eaton Corp. PLC"),
    ("@DENAULT_50060", "Leo Denault", "Entergy Corp."),
    ("@DICKERSON_75100", "Chad Dickerson", "Etsy Inc."),
    ("@SILVERMAN_91081", "Josh Silverman", "Etsy Inc."),
    ("@BASSHAM_53117", "Terry Bassham", "Evergy Inc."),
    ("@MUSSALLEM_49900", "Michael Mussallem", "Edwards Lifesciences Corp."),
    ("@CRANE_49982", "Christopher Crane", "Exelon Corp."),
    ("@PRAMAGGIORE_57006", "Anne Pramaggiore", "Exelon Corp."),
    ("@OBRIEN_57003", "Denis OBrien", "Exelon Corp."),
    ("@NIGRO_117573", "Joseph Nigro", "Exelon Corp."),
    ("@CORNEW_56986", "Kenneth Cornew", "Exelon Corp."),
    ("@MUSSER_57093", "Jeffrey Musser", "Expeditors International of Washington Inc."),
    ("@OKERSTROM_50011", "Mark Okerstrom", "Expedia Group Inc."),
    ("@KERN_60911", "Peter Kern", "Expedia Group Inc."),
    ("@KHOSROWSHAHI_50010", "Dara Khosrowshahi", "Expedia Group Inc."),
    ("@MARGOLIS_71690", "Joseph Margolis", "Extra Space Storage Inc."),
    ("@FIELDS_58110", "Mark Fields", "Ford Motor Co."),
    ("@HACKETT_171452", "James Hackett", "Ford Motor Co."),
    ("@FARLEY_77016", "James Farley", "Ford Motor Co."),
    ("@STICE_58377", "Travis Stice", "Diamondback Energy Inc."),
    ("@FLORNESS_49923", "Daniel Florness", "Fastenal Co."),
    ("@ZUCKERBERG_55643", "Mark Zuckerberg", "Facebook Inc."),
    ("@KLEIN_53301", "Christopher Klein", "Fortune Brands Home & Security Inc."),
    ("@FINK_86241", "Nicholas Fink", "Fortune Brands Home & Security Inc."),
    ("@ADKERSON_49934", "Richard Adkerson", "Freeport-McMoRan Inc."),
    ("@SMITH_49954", "Frederick Smith", "FedEx Corp."),
    ("@MAIER_171192", "Henry Maier", "FedEx Corp."),
    ("@CUNNINGHAM_173401", "David Cunningham", "FedEx Corp."),
    ("@COLLERAN_171394", "Donald Colleran", "FedEx Corp."),
    ("@JONES_60600", "Charles Jones", "FirstEnergy Corp."),
    ("@STRAH_90067", "Steven Strah", "FirstEnergy Corp."),
    ("@MCADAM_49949", "John McAdam", "F5 Networks Inc."),
    ("@DONOU_111022", "Francois Locoh-Donou", "F5 Networks Inc."),
    ("@NORCROSS_59465", "Gary Norcross", "Fidelity National Information Services Inc."),
    ("@YABUKI_49950", "Jeffery Yabuki", "Fiserv Inc."),
    ("@BISIGNANO_80884", "Frank Bisignano", "Fiserv Inc."),
    ("@CARMICHAEL_71370", "Greg Carmichael", "Fifth Third Bancorp"),
    ("@CLARKE_53376", "Ronald Clarke", "FleetCor Technologies Inc."),
    ("@NETTO_78343", "Armando Netto", "FleetCor Technologies Inc."),
    ("@BRONDEAU_49943", "Pierre Brondeau", "FMC Corp."),
    ("@GRAVES_49944", "Paul Graves", "FMC Corp."),
    ("@DOUGLAS_70366", "Mark Douglas", "FMC Corp."),
    ("@MURDOCH_60482", "Lachlan Murdoch", "Fox Corp."),
    ("@HERBERT_55491", "James Herbert", "First Republic Bank"),
    ("@WOOD_53276", "Donald Wood", "Federal Realty Investment Trust"),
    ("@XIE_53170", "Ken Xie", "Fortinet Inc."),
    ("@LICO_75990", "James Lico", "Fortive Corp."),
    ("@NOVAKOVIC_51659", "Phebe Novakovic", "General Dynamics Corp."),
    ("@IMMELT_49969", "Jeffrey Immelt", "General Electric Co."),
    ("@STOKES_183450", "Russell Stokes", "General Electric Co."),
    ("@FLANNERY_170356", "John Flannery", "General Electric Co."),
    ("@CULP_49851", "Lawrence Culp", "General Electric Co."),
    ("@STRAZIK_194472", "Scott Strazik", "General Electric Co."),
    ("@SLATTERY_194471", "John Slattery", "General Electric Co."),
    ("@MURPHY_123629", "Kieran Murphy", "General Electric Co."),
    ("@MILLIGAN_64590", "John Milligan", "Gilead Sciences Inc."),
    ("@ALTON_171240", "Gregg Alton", "Gilead Sciences Inc."),
    ("@ODAY_75444", "Daniel ODay", "Gilead Sciences Inc."),
    ("@POWELL_50038", "Kendall Powell", "General Mills Inc."),
    ("@HARMENING_80289", "Jeffrey Harmening", "General Mills Inc."),
    ("@HUDSON_85979", "Charles Hudson", "Torchmark Corp."),
    ("@COLEMAN_51224", "Gary Coleman", "Globe Life Inc."),
    ("@HUTCHISON_51226", "Larry Hutchison", "Globe Life Inc."),
    ("@SMITH_85978", "Roger Smith", "Torchmark Corp."),
    ("@GREER_176948", "Steven Greer", "Globe Life Inc."),
    ("@WEEKS_49978", "Wendell Weeks", "Corning Inc."),
    ("@BARRA_56842", "Mary Barra", "General Motors Co."),
    ("@AMMANN_53107", "Daniel Ammann", "General Motors Co."),
    ("@JAGDFELD_52959", "Aaron Jagdfeld", "Generac Holdings Inc."),
    ("@DONAHUE_71970", "Paul Donahue", "Genuine Parts Co."),
    ("@BREEN_86256", "Timothy Breen", "Genuine Parts Co."),
    ("@SLOAN_56607", "Jeffrey Sloan", "Global Payments Inc."),
    ("@PECK_59368", "Arthur Peck", "Gap Inc."),
    ("@BREITBARD_172051", "Mark Breitbard", "The Gap Inc."),
    ("@FISKE_150752", "Mcneil Fiske", "The Gap Inc."),
    ("@FISHER_60957", "Robert Fisher", "The Gap Inc."),
    ("@BREITBARD_172051", "Mark Breitbard", "The Gap Inc."),
    ("@SYNGAL_86928", "Sonia Syngal", "The Gap Inc."),
    ("@SYNGAL_86928", "Sonia Syngal", "Gap Inc."),
    ("@BREITBARD_172051", "Mark Breitbard", "The Gap Inc."),
    ("@GREEN_195302", "Nancy Green", "The Gap Inc."),
    ("@PEMBLE_50575", "Clifton Pemble", "Garmin Ltd."),
    ("@GNODDE_171046", "Richard Gnodde", "Goldman Sachs Group Inc."),
    ("@BLANKFEIN_50003", "Lloyd Blankfein", "Goldman Sachs Group Inc."),
    ("@SOLOMON_171045", "David Solomon", "Goldman Sachs Group Inc."),
    ("@MACPHERSON_77378", "Donald Macpherson", "W.W. Grainger Inc."),
    ("@LESAR_50046", "David Lesar", "Halliburton Co."),
    ("@MILLER_61651", "Jeffrey Miller", "Halliburton Co."),
    ("@THROOP_47987", "Darren Throop", "Hasbro Inc."),
    ("@GOLDNER_50120", "Brian Goldner", "Hasbro Inc."),
    ("@STEINOUR_50157", "Stephen Steinour", "Huntington Bancshares Inc."),
    ("@EVANS_77644", "Gerald Evans", "Hanesbrands Inc."),
    ("@BRATSPIES_193644", "Stephen Bratspies", "Hanesbrands Inc."),
    ("@JOHNSON_53001", "Milton Johnson", "HCA Healthcare Inc."),
    ("@HAZEN_77471", "Samuel Hazen", "HCA Healthcare Inc."),
    ("@MENEAR_59022", "Craig Menear", "The Home Depot Inc."),
    ("@HESS_50096", "John Hess", "Hess Corp."),
    ("@SWIFT_50091", "Christopher Swift", "The Hartford Financial Services Group Inc."),
    ("@PETTERS_53174", "Michael Petters", "Huntington Ingalls Industries Inc."),
    ("@NASSETTA_57062", "Christopher Nassetta", "Hilton Worldwide Holdings Inc."),
    ("@MACMILLAN_56833", "Stephen MacMillan", "Hologic Inc."),
    ("@COTE_49981", "David Cote", "Honeywell International Inc."),
    ("@GAUTAM_170252", "Rajeev Gautam", "Honeywell International Inc."),
    ("@ADAMCZYK_88059", "Darius Adamczyk", "Honeywell International Inc."),
    ("@WALDRON_196662", "John Waldron", "Honeywell International Inc."),
    ("@MAHONEY_85885", "Timothy Mahoney", "Honeywell International Inc."),
    ("@WHITMAN_50100", "Margaret Whitman", "Hewlett Packard Enterprise Co."),
    ("@NERI_89597", "Antonio Neri", "Hewlett Packard Enterprise Co."),
    ("@WEISLER_77216", "Dion Weisler", "HP Inc."),
    ("@LORES_169897", "Enrique Lores", "HP Inc."),
    ("@SNEE_85685", "James Snee", "Hormel Foods Corp."),
    ("@BERGMAN_52724", "Stanley Bergman", "Henry Schein Inc."),
    ("@RISOLEO_86889", "James Risoleo", "Host Hotels & Resorts Inc."),
    ("@BUCK_77550", "Michele Buck", "The Hershey Co."),
    ("@BROUSSARD_50147", "Bruce Broussard", "Humana Inc."),
    ("@KLEINFELD_49484", "Klaus Kleinfeld", "Arconic Inc."),
    ("@HESS_97638", "David Hess", "Arconic Inc."),
    ("@PLANT_51222", "John Plant", "Howmet Aerospace Inc."),
    ("@OAL_197011", "Tolga Oal", "Howmet Aerospace Inc."),
    ("@ROMETTY_51688", "Virginia Rometty", "International Business Machines Corp."),
    ("@KRISHNA_193450", "Arvind Krishna", "International Business Machines Corp."),
    ("@SPRECHER_50088", "Jeffrey Sprecher", "Intercontinental Exchange Inc."),
    ("@AYERS_53024", "Jonathan Ayers", "IDEXX Laboratories Inc."),
    ("@MAZELSKY_80146", "Jay Mazelsky", "IDEXX Laboratories Inc."),
    ("@MAZELSKY_80146", "Jay Mazelsky", "IDEXX Laboratories Inc."),
    ("@SILVERNAIL_53040", "Andrew Silvernail", "IDEX Corp."),
    ("@ASHLEMAN_80154", "Eric Ashleman", "IDEX Corp."),
    ("@FIBIG_58226", "Andreas Fibig", "International Flavors & Fragrances Inc."),
    ("@DESOUZA_59714", "Francis DeSouza", "Illumina Inc."),
    ("@HOPPENOT_57294", "Herve Hoppenot", "Incyte Corp."),
    ("@STEAD_133566", "Jerre Stead", "IHS Markit Ltd."),
    ("@UGGLA_133570", "Lance Uggla", "IHS Markit Ltd."),
    ("@KRZANICH_50075", "Brian Krzanich", "Intel Corp."),
    ("@SWAN_166673", "Robert Swan", "Intel Corp."),
    ("@SWAN_166673", "Robert Swan", "Intel Corp."),
    ("@SMITH_50123", "Brad Smith", "Intuit Inc."),
    ("@GOODARZI_77246", "Sasan Goodarzi", "Intuit Inc."),
    ("@SUTTON_59238", "Mark Sutton", "International Paper Co."),
    ("@ROTH_50114", "Michael Roth", "The Interpublic Group of Companies Inc."),
    ("@KRAKOWSKY_58743", "Philippe Krakowsky", "The Interpublic Group of Companies Inc."),
    ("@GAPONTSEV_52723", "Valentin Gapontsev", "IPG Photonics Corp."),
    ("@SCHERBAKOV_66027", "Eugene Scherbakov", "IPG Photonics Corp."),
    ("@BOUSBIB_58255", "Ari Bousbib", "IQVIA Holdings Inc."),
    ("@REYNAL_163345", "Vicente Reynal", "Ingersoll Rand Inc."),
    ("@MEANEY_50164", "William Meaney", "Iron Mountain Inc."),
    ("@GUTHART_50134", "Gary Guthart", "Intuitive Surgical Inc."),
    ("@HALL_52672", "Eugene Hall", "Gartner Inc."),
    ("@SANTI_50177", "Scott Santi", "Illinois Tool Works Inc."),
    ("@FLANAGAN_50151", "Martin Flanagan", "Invesco Ltd."),
    ("@DEMETRIOU_68720", "Steven Demetriou", "Jacobs Engineering Group Inc."),
    ("@MANDEL_80199", "Joseph Mandel", "Jacobs Engineering Group Inc."),
    ("@ROBERTS_52784", "John Roberts", "J.B. Hunt Transport Services Inc."),
    ("@OLIVER_50584", "George Oliver", "Johnson Controls International PLC"),
    ("@FOSS_85222", "David Foss", "Jack Henry & Associates Inc."),
    ("@GORSKY_50128", "Alex Gorsky", "Johnson & Johnson Services Inc."),
    ("@RAHIM_59681", "Rami Rahim", "Juniper Networks Inc."),
    ("@DIMON_50168", "James Dimon", "JPMorgan Chase & Co."),
    ("@PINTO_77258", "Daniel Pinto", "JPMorgan Chase & Co."),
    ("@ERDOES_77255", "Mary Erdoes", "JPMorgan Chase & Co."),
    ("@BRYANT_50140", "John Bryant", "Kellogg Co."),
    ("@CAHILLANE_170181", "Steven Cahillane", "Kellogg Co."),
    ("@MOONEY_50145", "Beth Mooney", "KeyCorp."),
    ("@GORMAN_77204", "Christopher Gorman", "KeyCorp."),
    ("@NERSESIAN_65730", "Ronald Nersesian", "Keysight Technologies Inc."),
    ("@PATRICIO_183989", "Miguel Patricio", "The Kraft Heinz Co."),
    ("@HEES_50124", "Bernardo Hees", "The Kraft Heinz Co."),
    ("@FLYNN_72135", "Conor Flynn", "Kimco Realty Corp."),
    ("@WALLACE_50175", "Richard Wallace", "KLA Corp."),
    ("@STEIMBERG_181053", "Amichai Steimberg", "KLA Corp."),
    ("@FALK_50153", "Thomas Falk", "Kimberly-Clark Corp."),
    ("@HSU_77584", "Michael Hsu", "Kimberly-Clark Corp."),
    ("@KEAN_60225", "Steven Kean", "Kinder Morgan Inc."),
    ("@NASH_77545", "William Nash", "CarMax Inc."),
    ("@KENT_52705", "Muhtar Kent", "The Coca-Cola Co."),
    ("@QUINCEY_86379", "James Quincey", "The Coca-Cola Co."),
    ("@MCMULLEN_57625", "W. McMullen", "The Kroger Co."),
    ("@OTTENSMEYER_77642", "Patrick Ottensmeyer", "Kansas City Southern"),
    ("@TISCH_50235", "James Tisch", "Loews Corp."),
    ("@KRONE_58456", "Roger Krone", "Leidos Holdings Inc."),
    ("@GLASSMAN_62299", "Karl Glassman", "Leggett & Platt Inc."),
    ("@MILLER_50163", "Stuart Miller", "Lennar Corp."),
    ("@GROSS_50165", "Bruce Gross", "Lennar Corp."),
    ("@BECKWITT_68120", "Richard Beckwitt", "Lennar Corp."),
    ("@JAFFE_77569", "Jonathan Jaffe", "Lennar Corp."),
    ("@KING_50173", "David King", "Laboratory Corp. of America Holdings"),
    ("@RATLIFF_171825", "John Ratliff", "Laboratory Corp. of America Holdings"),
    ("@HUFF_171830", "Gary Huff", "Laboratory Corp. of America Holdings"),
    ("@SCHECHTER_62415", "Adam Schechter", "Laboratory Corp. of America Holdings"),
    ("@KIRCHGRABER_195984", "Paul Kirchgraber", "Laboratory Corp. of America Holdings"),
    ("@BROWN_50093", "William Brown", "L3Harris Technologies Inc"),
    ("@KUBASIK_133633", "Christopher Kubasik", "L3Harris Technologies Inc"),
    ("@ANGEL_50449", "Stephen Angel", "Linde PLC"),
    ("@QUINN_52606", "John Quinn", "LKQ Corp."),
    ("@ZARCONE_72171", "Dominick Zarcone", "LKQ Corp."),
    ("@RICKS_131701", "David Ricks", "Eli Lilly and Co."),
    ("@HEWSON_50230", "Marillyn Hewson", "Lockheed Martin Corp."),
    ("@TAICLET_49421", "James Taiclet", "Lockheed Martin Corp."),
    ("@GLASS_50203", "Dennis Glass", "Lincoln National Corp."),
    ("@KAMPLING_52578", "Patricia Kampling", "Alliant Energy Corp."),
    ("@LARSEN_78583", "John Larsen", "Alliant Energy Corp."),
    ("@NIBLOCK_50276", "Robert Niblock", "Lowe's Companies Inc."),
    ("@ELLISON_59392", "Marvin Ellison", "Lowe's Companies Inc."),
    ("@ANSTICE_50192", "Martin Anstice", "Lam Research Corp."),
    ("@ARCHER_77635", "Timothy Archer", "Lam Research Corp."),
    ("@POST_49810", "Glen Post", "CenturyLink Inc."),
    ("@STOREY_52593", "Jeff Storey", "Lumen Technologies Inc."),
    ("@KELLY_50506", "Gary Kelly", "Southwest Airlines Co."),
    ("@ADELSON_52599", "Sheldon Adelson", "Las Vegas Sands Corp."),
    ("@GOLDSTEIN_70677", "Robert Goldstein", "Las Vegas Sands Corp."),
    ("@GOLDSTEIN_70677", "Robert Goldstein", "Las Vegas Sands Corp."),
    ("@WERNER_88283", "Thomas Werner", "Lamb Weston Holdings Inc."),
    ("@PATEL_63305", "Bhavesh Patel", "LyondellBasell Industries N.V."),
    ("@RAPINO_52383", "Michael Rapino", "Live Nation Entertainment Inc."),
    ("@BANGA_50278", "Ajay Banga", "MasterCard Inc."),
    ("@MIEBACH_185671", "Michael Miebach", "MasterCard Inc."),
    ("@BOLTON_52398", "H. Bolton", "Mid America Apartment Communities Inc."),
    ("@SORENSON_50283", "Arne Sorenson", "Marriott International Inc."),
    ("@CAPUANO_77104", "Anthony Capuano", "Marriott International Inc."),
    ("@LINNARTZ_90184", "Stephanie Linnartz", "Marriott International Inc."),
    ("@ALLMAN_57270", "Keith Allman", "Masco Corp."),
    ("@EASTERBROOK_69328", "Stephen Easterbrook", "McDonald's Corp."),
    ("@KEMPCZINSKI_87243", "Christopher Kempczinski", "McDonald's Corp."),
    ("@SANGHI_50256", "Steve Sanghi", "Microchip Technology Inc."),
    ("@MOORTHY_71286", "Ganesh Moorthy", "Microchip Technology Inc."),
    ("@HAMMERGREN_50240", "John Hammergren", "McKesson Corp."),
    ("@TYLER_173134", "Brian Tyler", "McKesson Corp."),
    ("@MCDANIEL_50303", "Raymond McDaniel", "Moody's Corp."),
    ("@FAUBER_58744", "Robert Fauber", "Moody's Corp."),
    ("@ROSENFELD_50244", "Irene Rosenfeld", "Mondelez International Inc."),
    ("@PUT_60373", "Dirk Van De Put", "Mondelez International Inc."),
    ("@ISHRAK_50286", "Omar Ishrak", "Medtronic PLC"),
    ("@MARTHA_181747", "Geoffrey Martha", "Medtronic PLC"),
    ("@KANDARIAN_50225", "Steven Kandarian", "MetLife Inc."),
    ("@KHALAF_172770", "Michel Khalaf", "MetLife Inc."),
    ("@MURREN_52287", "James Murren", "MGM Resorts International"),
    ("@HORNBUCKLE_78605", "William Hornbuckle", "MGM Resorts International"),
    ("@HORNBUCKLE_78605", "William Hornbuckle", "MGM Resorts International"),
    ("@LORBERBAUM_52318", "Jeffrey Lorberbaum", "Mohawk Industries Inc."),
    ("@KURZIUS_77654", "Lawrence Kurzius", "McCormick & Co. Inc."),
    ("@MCVEY_52344", "Richard McVey", "MarketAxess Holdings Inc."),
    ("@NYE_52388", "Howard Nye", "Martin Marietta Materials Inc."),
    ("@GLASER_50316", "Daniel Glaser", "Marsh & McLennan Companies Inc."),
    ("@PORTALATIN_77120", "Julio Portalatin", "Marsh & McLennan Companies Inc."),
    ("@DOYLE_171582", "John Doyle", "Marsh & McLennan Companies Inc."),
    ("@THULIN_49438", "Inge Thulin", "3M Co."),
    ("@ROMAN_89859", "Michael Roman", "3M Co."),
    ("@SACKS_50280", "Rodney Sacks", "Monster Beverage Corp."),
    ("@SCHLOSBERG_50281", "Hilton Schlosberg", "Monster Beverage Corp."),
    ("@BARRINGTON_49545", "Martin Barrington", "Altria Group Inc."),
    ("@WILLARD_47631", "Howard Willard", "Altria Group Inc."),
    ("@GIFFORD_58609", "William Gifford", "Altria Group Inc."),
    ("@JOHNSON_77145", "Craig Johnson", "Altria Group Inc."),
    ("@GIFFORD_58609", "William Gifford", "Altria Group Inc."),
    ("@O'ROURKE_48263", "James O'rourke", "The Mosaic Co."),
    ("@HEMINGER_50242", "Gary Heminger", "Marathon Petroleum Corp."),
    ("@HENNIGAN_55912", "Michael Hennigan", "Marathon Petroleum Corp."),
    ("@HSING_52393", "Michael Hsing", "Monolithic Power Systems Inc."),
    ("@FRAZIER_50209", "Kenneth Frazier", "Merck & Co. Inc."),
    ("@BATRA_132675", "Udit Batra", "Merck KGaA"),
    ("@DAVIS_57908", "Robert Davis", "Merck & Co. Inc."),
    ("@BANCEL_60218", "Stephane Bancel", "Moderna Inc."),
    ("@TILLMAN_90846", "Lee Tillman", "Marathon Oil Corp."),
    ("@GORMAN_50290", "James Gorman", "Morgan Stanley"),
    ("@KELLEHER_77193", "Colm Kelleher", "Morgan Stanley"),
    ("@FERNANDEZ_52024", "Henry Fernandez", "MSCI Inc."),
    ("@NADELLA_57519", "Satya Nadella", "Microsoft Corp."),
    ("@BROWN_50357", "Gregory Brown", "Motorola Solutions Inc."),
    ("@WILMERS_52215", "Robert Wilmers", "M&T Bank Corp."),
    ("@JONES_52217", "Rene Jones", "M&T Bank Corp."),
    ("@LEVIN_67755", "Joseph Levin", "Match Group Inc."),
    ("@GINSBERG_76200", "Amanda Ginsberg", "Match Group Inc."),
    ("@THOMBRE_87508", "Amarnath Thombre", "Match Group Inc."),
    ("@DUBEY_179052", "Sharmistha Dubey", "Match Group Inc."),
    ("@FILLIOL_52225", "Olivier Filliol", "Mettler-Toledo International Inc."),
    ("@DURCAN_50250", "Mark Durcan", "Micron Technology Inc."),
    ("@MEHROTRA_50515", "Sanjay Mehrotra", "Micron Technology Inc."),
    ("@RIO_66497", "Frank Del Rio", "Norwegian Cruise Line Holdings Ltd."),
    ("@STUART_78847", "Andrew Stuart", "Norwegian Cruise Line Holdings Ltd."),
    ("@MONTAGUE_87004", "Jason Montague", "Norwegian Cruise Line Holdings Ltd."),
    ("@BINDER_87007", "Robert Binder", "Norwegian Cruise Line Holdings Ltd."),
    ("@SOMMER_92680", "Harry Sommer", "Norwegian Cruise Line Holdings Ltd."),
    ("@FRIEDMAN_55820", "Adena Friedman", "NASDAQ Inc."),
    ("@ROBO_50325", "James Robo", "NextEra Energy Inc."),
    ("@SILAGY_86818", "Eric Silagy", "NextEra Energy Inc."),
    ("@KETCHUM_71893", "John Ketchum", "NextEra Energy Inc."),
    ("@PIMENTEL_77572", "Armando Pimentel", "NextEra Energy Inc."),
    ("@GOLDBERG_48304", "Gary Goldberg", "Newmont Goldcorp Corp."),
    ("@PALMER_89680", "Thomas Palmer", "Newmont Corp."),
    ("@HASTINGS_50376", "Reed Hastings", "Netflix Inc."),
    ("@SARANDOS_77400", "Ted Sarandos", "Netflix Inc."),
    ("@HAMROCK_75284", "Joseph Hamrock", "NiSource Inc."),
    ("@PARKER_50328", "Mark Parker", "NIKE Inc."),
    ("@DONAHOE_49868", "John Donahoe", "NIKE Inc."),
    ("@CLARK_99363", "Gregory Clark", "Symantec Corp."),
    ("@PILETTE_135890", "Vincent Pilette", "NortonLifeLock Inc."),
    ("@BARNS_56740", "Dwight Barns", "Nielsen Holdings PLC"),
    ("@KENNY_61437", "David Kenny", "Nielsen Holdings PLC"),
    ("@RAWLINSON_106151", "David Rawlinson", "Nielsen Holdings PLC"),
    ("@BUSH_50352", "Wesley Bush", "Northrop Grumman Corp."),
    ("@WARDEN_86830", "Kathy Warden", "Northrop Grumman Corp."),
    ("@DONAHOE_49868", "John Donahoe", "ServiceNow Inc."),
    ("@MCDERMOTT_48991", "William McDermott", "ServiceNow Inc."),
    ("@GUTIERREZ_69653", "Mauricio Gutierrez", "NRG Energy Inc."),
    ("@SQUIRES_62541", "James Squires", "Norfolk Southern Corp."),
    ("@KURIAN_75266", "George Kurian", "NetApp Inc."),
    ("@WADDELL_50340", "Frederick Waddell", "Northern Trust Corp."),
    ("@O'GRADY_50341", "Michael O'Grady", "Northern Trust Corp."),
    ("@FERRIOLA_50324", "John Ferriola", "Nucor Corp."),
    ("@TOPALIAN_183736", "Leon Topalian", "Nucor Corp."),
    ("@HUANG_50333", "Jen-Hsun Huang", "NVIDIA Corp."),
    ("@SAVILLE_52142", "Paul Saville", "NVR Inc."),
    ("@POLK_50272", "Michael Polk", "Newell Brands Inc."),
    ("@PETERSON_172691", "Christopher Peterson", "Newell Brands Inc."),
    ("@SALIGRAM_52137", "Ravichandra Saligram", "Newell Brands Inc."),
    ("@MALKOSKI_194595", "Kristine Malkoski", "Newell Brands Inc."),
    ("@CLEMMER_58051", "Richard Clemmer", "NXP Semiconductors N.V."),
    ("@SIEVERS_191663", "Kurt Sievers", "NXP Semiconductors N.V."),
    ("@CASE_56501", "John Case", "Realty Income Corp."),
    ("@ROY_77557", "Sumit Roy", "Realty Income Corp."),
    ("@CONGDON_52268", "David Congdon", "Old Dominion Freight Line Inc."),
    ("@GANTT_78900", "Greg Gantt", "Old Dominion Freight Line Inc."),
    ("@SPENCER_56637", "Terry Spencer", "ONEOK Inc."),
    ("@NORTON_59319", "Pierce Norton", "ONEOK Inc."),
    ("@WREN_50298", "John Wren", "Omnicom Group Inc."),
    ("@NELSON_77352", "Jonathan Nelson", "Omnicom Group Inc."),
    ("@CATZ_46794", "Safra Catz", "Oracle Corp."),
    ("@HURD_59275", "Mark Hurd", "Oracle Corp."),
    ("@HENSLEE_50453", "Greg Henslee", "O'Reilly Automotive Inc."),
    ("@JOHNSON_88174", "Greg Johnson", "O'Reilly Automotive Inc."),
    ("@MARKS_85637", "Judith Marks", "Otis Worldwide Corp."),
    ("@HOLLUB_77199", "Vicki Hollub", "Occidental Petroleum Corp."),
    ("@RICHISON_58262", "Chad Richison", "Paycom Software Inc."),
    ("@MUCCI_50330", "Martin Mucci", "Paychex Inc."),
    ("@BARNES_52136", "John Barnes", "People's United Financial Inc."),
    ("@ARMSTRONG_56974", "Ronald Armstrong", "PACCAR Inc."),
    ("@FEIGHT_177077", "R. Feight", "PACCAR Inc."),
    ("@HERZOG_51068", "Thomas Herzog", "Healthpeak Properties Inc."),
    ("@IZZO_50445", "Ralph Izzo", "Public Service Enterprise Group Inc."),
    ("@WILMOTT_56812", "Timothy Wilmott", "Penn National Gaming Inc."),
    ("@SNOWDEN_78865", "Jay Snowden", "Penn National Gaming Inc."),
    ("@NOOYI_50370", "Indra Nooyi", "PepsiCo Inc."),
    ("@LAGUARTA_86520", "Ramon Laguarta", "PepsiCo Inc."),
    ("@CAREY_61286", "Albert Carey", "PepsiCo Inc."),
    ("@LAGUARTA_86520", "Ramon Laguarta", "PepsiCo Inc."),
    ("@TANNER_183619", "Kirk Tanner", "PepsiCo Inc."),
    ("@POPOVICI_177189", "Silviu Popovici", "PepsiCo Inc."),
    ("@CHADHA_77043", "Sanjeev Chadha", "PepsiCo Inc."),
    ("@READ_50392", "Ian Read", "Pfizer Inc."),
    ("@BOURLA_89790", "Albert Bourla", "Pfizer Inc."),
    ("@MCCAUGHAN_79289", "James McCaughan", "Principal Financial Group Inc."),
    ("@HOUSTON_62695", "Daniel Houston", "Principal Financial Group Inc."),
    ("@HALTER_178118", "Patrick Halter", "Principal Financial Group Inc."),
    ("@TAYLOR_69171", "David Taylor", "Procter & Gamble Co."),
    ("@MCHUGH_75297", "Mary Lynn Ferguson-Mchugh", "Procter & Gamble Co."),
    ("@BISHOP_88345", "Steven Bishop", "Procter & Gamble Co."),
    ("@GRIFFITH_67130", "Susan Griffith", "The Progressive Corp."),
    ("@AUER_86715", "John Auer", "The Progressive Corp."),
    ("@WILLIAMS_66953", "Thomas Williams", "Parker-Hannifin Corp."),
    ("@MARSHALL_77459", "Ryan Marshall", "PulteGroup Inc."),
    ("@KOWLZAN_52079", "Mark Kowlzan", "Packaging Corp. of America"),
    ("@FRIEL_50308", "Robert Friel", "PerkinElmer Inc."),
    ("@SINGH_89698", "Prahlad Singh", "PerkinElmer Inc."),
    ("@MOGHADAM_50568", "Hamid Moghadam", "Prologis Inc."),
    ("@REILLY_70919", "Eugene Reilly", "Prologis Inc."),
    ("@ANDERSON_62604", "Gary Anderson", "Prologis Inc."),
    ("@CALANTZOPOULOS_60208", "Andre Calantzopoulos", "Philip Morris International Inc."),
    ("@KING_77056", "Martin King", "Philip Morris International Inc."),
    ("@OLCZAK_50361", "Jacek Olczak", "Philip Morris International Inc."),
    ("@DEMCHAK_50398", "William Demchak", "The PNC Financial Services Group Inc."),
    ("@HOGAN_50594", "Randall Hogan", "Pentair PLC"),
    ("@STAUCH_50595", "John Stauch", "Pentair PLC"),
    ("@BRANDT_50379", "Donald Brandt", "Pinnacle West Capital Corp."),
    ("@GULDNER_177171", "Jeffrey Guldner", "Pinnacle West Capital Corp."),
    ("@MESA_51759", "Manuel Perez de la Mesa", "Pool Corp."),
    ("@ARVAN_171533", "Peter Arvan", "Pool Corp."),
    ("@MCGARRY_70736", "Michael McGarry", "PPG Industries Inc."),
    ("@SYMONS_77197", "Robert Symons", "PPL Corp."),
    ("@SPENCE_50431", "William Spence", "PPL Corp."),
    ("@THOMPSON_177932", "Paul Thompson", "PPL Corp."),
    ("@SORGI_58369", "Vincent Sorgi", "PPL Corp."),
    ("@STRANGFELD_50405", "John Strangfeld", "Prudential Financial Inc."),
    ("@LOWREY_77319", "Charles Lowrey", "Prudential Financial Inc."),
    ("@HAVNER_50478", "Ronald Havner", "Public Storage"),
    ("@RUSSELL_51861", "Joseph Russell", "Public Storage"),
    ("@GARLAND_51907", "Greg Garland", "Phillips 66"),
    ("@HEPPELMANN_51870", "James Heppelmann", "PTC Inc."),
    ("@CHIRICO_50532", "Emanuel Chirico", "PVH Corp."),
    ("@GRIEDER_77506", "Daniel Grieder", "PVH Corp."),
    ("@LARSSON_77388", "Stefan Larsson", "PVH Corp."),
    ("@DUANE_77505", "Francis Duane", "PVH Corp."),
    ("@SHIFFMAN_77509", "Steve Shiffman", "PVH Corp."),
    ("@AUSTIN_77269", "Earl Austin", "Quanta Services Inc."),
    ("@DOVE_61597", "Timothy Dove", "Pioneer Natural Resources Co."),
    ("@SHEFFIELD_50386", "Scott Sheffield", "Pioneer Natural Resources Co."),
    ("@SCHULMAN_60557", "Daniel Schulman", "PayPal Holdings Inc."),
    ("@MOLLENKOPF_56865", "Steven Mollenkopf", "QUALCOMM Inc."),
    ("@AMON_77073", "Cristiano Amon", "QUALCOMM Inc."),
    ("@BRUGGEWORTH_51830", "Robert Bruggeworth", "Qorvo Inc."),
    ("@FAIN_51721", "Richard Fain", "Royal Caribbean Cruises Ltd."),
    ("@PERLO_90996", "Lisa Lutoff-Perlo", "Royal Caribbean Cruises Ltd."),
    ("@BAYLEY_79428", "Michael Bayley", "Royal Caribbean Cruises Ltd."),
    ("@ADDESSO_58384", "Dominic Addesso", "Everest Re Group Ltd."),
    ("@DOUCETTE_79969", "John Doucette", "Everest Re Group Ltd."),
    ("@ANDRADE_196581", "Juan Andrade", "Everest Re Group Ltd."),
    ("@DOUCETTE_79969", "John Doucette", "Everest Re Group Ltd."),
    ("@STEIN_51750", "Martin Stein", "Regency Centers Corp."),
    ("@PALMER_51751", "Lisa Palmer", "Regency Centers Corp."),
    ("@SCHLEIFER_51769", "Leonard Schleifer", "Regeneron Pharmaceuticals Inc."),
    ("@HALL_50476", "O.B. Hall", "Regions Financial Corp."),
    ("@TURNER_170280", "John Turner", "Regions Financial Corp."),
    ("@MESSMER_54490", "Harold Messmer", "Robert Half International Inc."),
    ("@WADDELL_54491", "Keith Waddell", "Robert Half International Inc."),
    ("@GENTZKOW_77403", "Paul Gentzkow", "Robert Half International Inc."),
    ("@REILLY_51669", "Paul Reilly", "Raymond James Financial Inc."),
    ("@ZANK_78897", "Dennis Zank", "Raymond James Financial Inc."),
    ("@LAUREN_50601", "Ralph Lauren", "Ralph Lauren Corp."),
    ("@LARSSON_77388", "Stefan Larsson", "Ralph Lauren Corp."),
    ("@LOUVET_88346", "Patrice Louvet", "Ralph Lauren Corp."),
    ("@FARRELL_51822", "Michael Farrell", "ResMed Inc."),
    ("@MORET_79454", "Blake Moret", "Rockwell Automation Inc."),
    ("@ROLLINS_51610", "Gary Rollins", "Rollins Inc."),
    ("@JELLISON_50410", "Brian Jellison", "Roper Technologies Inc."),
    ("@HUNN_172529", "L. Hunn", "Roper Technologies Inc."),
    ("@RENTLER_58176", "Barbara Rentler", "Ross Stores Inc."),
    ("@SLAGER_50496", "Donald Slager", "Republic Services Inc."),
    ("@ARK_177753", "Jon Vander Ark", "Republic Services Inc."),
    ("@HAYES_50685", "Gregory Hayes", "Raytheon Technologies Corp."),
    ("@GITLIN_177230", "David Gitlin", "Raytheon Technologies Corp."),
    ("@DARNIS_77044", "Geraud Darnis", "United Technologies Corp."),
    ("@STOOPS_165665", "Jeffrey Stoops", "SBA Communications Corp."),
    ("@SCHULTZ_50570", "Howard Schultz", "Starbucks Corp."),
    ("@JOHNSON_50131", "Kevin Johnson", "Starbucks Corp."),
    ("@BETTINGER_50409", "Walter Bettinger", "The Charles Schwab Corp."),
    ("@CHANDOHA_86777", "Marie Chandoha", "The Charles Schwab Corp."),
    ("@PERIBERE_50481", "Jerome Peribere", "Sealed Air Corp."),
    ("@DOHENY_57033", "Edward Doheny", "Sealed Air Corp."),
    ("@MORIKIS_68622", "John Morikis", "The Sherwin-Williams Co."),
    ("@BECKER_51573", "Greg Becker", "SVB Financial Group"),
    ("@SMUCKER_100384", "Mark Smucker", "The J.M. Smucker Co."),
    ("@KIBSGAARD_50554", "Paal Kibsgaard", "Schlumberger Ltd."),
    ("@PEUCH_170146", "Olivier Le Peuch", "Schlumberger Ltd."),
    ("@PINCHUK_50574", "Nicholas Pinchuk", "Snap-on Inc."),
    ("@GEUS_51496", "Aart De Geus", "Synopsys Inc."),
    ("@CHAN_51498", "Chi-Foon Chan", "Synopsys Inc."),
    ("@FANNING_50471", "Thomas Fanning", "Southern Co."),
    ("@CROSSWHITE_87016", "Mark Crosswhite", "Southern Co."),
    ("@KUCZYNSKI_77303", "Stephen Kuczynski", "Southern Co."),
    ("@CROSSWHITE_87016", "Mark Crosswhite", "Southern Co."),
    ("@EVANS_49604", "Andrew Evans", "Southern Co."),
    ("@BOWERS_62355", "Paul Bowers", "Southern Co."),
    ("@KUCZYNSKI_77303", "Stephen Kuczynski", "Southern Co."),
    ("@SIMON_50556", "David Simon", "Simon Property Group Inc."),
    ("@MATTURRI_86433", "Alex Matturri", "S&P Global Inc."),
    ("@PETERSON_56624", "Douglas Peterson", "S&P Global Inc."),
    ("@REED_50488", "Debra Reed", "Sempra Energy"),
    ("@MARTIN_93658", "Jeffrey Martin", "Sempra Energy"),
    ("@ROSEBROUGH_135844", "Walter Rosebrough", "Steris PLC"),
    ("@CARESTIO_161433", "Daniel Carestio", "Steris PLC"),
    ("@HOOLEY_50429", "Joseph Hooley", "State Street Corp."),
    ("@TARAPOREVALA_171859", "Cyrus Taraporevala", "State Street Corp."),
    ("@OHANLEY_72199", "Ronald OHanley", "State Street Corp."),
    ("@ARISTEGUIETA_184437", "Francisco Aristeguieta", "State Street Corp."),
    ("@LUCZO_50459", "Stephen Luczo", "Seagate Technology PLC"),
    ("@MOSLEY_77430", "William Mosley", "Seagate Technology PLC"),
    ("@SANDS_49882", "Robert Sands", "Constellation Brands Inc."),
    ("@WRIGHT_77302", "John Wright", "Constellation Brands Inc."),
    ("@NEWLANDS_172276", "William Newlands", "Constellation Brands Inc."),
    ("@LOREE_68866", "James Loree", "Stanley Black & Decker Inc."),
    ("@GRIFFIN_67027", "Liam Griffin", "Skyworks Solutions Inc."),
    ("@KEANE_58803", "Margaret Keane", "Synchrony Financial"),
    ("@QUINDLEN_79964", "Thomas Quindlen", "Synchrony Financial"),
    ("@MEHTA_129113", "Neeraj Mehta", "Synchrony Financial"),
    ("@DOUBLES_58802", "Brian Doubles", "Synchrony Financial"),
    ("@MARINO_79957", "Glenn Marino", "Synchrony Financial"),
    ("@LOBO_50474", "Kevin Lobo", "Stryker Corp."),
    ("@DELANEY_50418", "William DeLaney", "Sysco Corp."),
    ("@BENE_77433", "Thomas Bene", "Sysco Corp."),
    ("@HOURICAN_188457", "Kevin Hourican", "Sysco Corp."),
    ("@STEPHENSON_49528", "Randall Stephenson", "AT & T Inc."),
    ("@DONOVAN_71629", "John Donovan", "AT & T Inc."),
    ("@STANKEY_58693", "John Stankey", "AT & T Inc."),
    ("@MCELFRESH_183370", "Jeffery McElfresh", "AT & T Inc."),
    ("@STANKEY_58693", "John Stankey", "AT & T Inc."),
    ("@KILAR_193540", "Jason Kilar", "AT & T Inc."),
    ("@HUNTER_58716", "Mark Hunter", "Molson Coors Brewing Co."),
    ("@COX_178050", "Simon Cox", "Molson Coors Beverage Co."),
    ("@HATTERSLEY_50232", "Gavin Hattersley", "Molson Coors Beverage Co."),
    ("@GLENDINNING_57173", "Stewart Glendinning", "Molson Coors Brewing Co."),
    ("@HATTERSLEY_50232", "Gavin Hattersley", "Molson Coors Beverage Co."),
    ("@HOWLEY_51352", "W. Howley", "TransDigm Group Inc."),
    ("@STEIN_86184", "Kevin Stein", "TransDigm Group Inc."),
    ("@MEHRABIAN_51321", "Robert Mehrabian", "Teledyne Technologies Inc."),
    ("@PICHELLI_79422", "Aldo Pichelli", "Teledyne Technologies Inc."),
    ("@KUMMETH_57185", "Charles Kummeth", "Bio-Techne Corp."),
    ("@CURTIN_77141", "Terrence Curtin", "TE Connectivity Ltd."),
    ("@JAGIELA_56758", "Mark Jagiela", "Teradyne Inc."),
    ("@KING_49613", "Kelly King", "Truist Financial Corp."),
    ("@SMITH_51372", "Benson Smith", "Teleflex Inc."),
    ("@KELLY_78914", "Liam Kelly", "Teleflex Inc."),
    ("@CORNELL_58760", "Brian Cornell", "Target Corp."),
    ("@HERRMAN_77525", "Ernie Herrman", "The TJX Companies Inc."),
    ("@CASPER_50457", "Marc Casper", "Thermo Fisher Scientific Inc."),
    ("@LEGERE_51923", "John Legere", "T-Mobile US Inc."),
    ("@SIEVERT_78990", "Michael Sievert", "T-Mobile US Inc."),
    ("@LUIS_57074", "Victor Luis", "Tapestry Inc."),
    ("@ZEITLIN_61222", "Jide Zeitlin", "Tapestry Inc."),
    ("@CREVOISERAT_58010", "Joanne Crevoiserat", "Tapestry Inc."),
    ("@KAHN_49770", "Todd Kahn", "Tapestry Inc."),
    ("@CREVOISERAT_58010", "Joanne Crevoiserat", "Tapestry Inc."),
    ("@BERGLUND_51218", "Steven Berglund", "Trimble Inc."),
    ("@PAINTER_85502", "Robert Painter", "Trimble Inc."),
    ("@STROMBERG_75056", "William Stromberg", "T. Rowe Price Group Inc."),
    ("@ALDERSON_86538", "Christopher Alderson", "T. Rowe Price Group Inc."),
    ("@SCHNITZER_76556", "Alan Schnitzer", "The Travelers Companies Inc."),
    ("@SANDFORT_51234", "Gregory Sandfort", "Tractor Supply Co."),
    ("@LEWIS_47546", "David Lewis", "Tesco PLC"),
    ("@LAWTON_86651", "Harry Lawton", "Tractor Supply Co."),
    ("@MUSK_51244", "Elon Musk", "Tesla Inc."),
    ("@HAYES_89307", "Thomas Hayes", "Tyson Foods Inc."),
    ("@WHITE_77345", "Noel White", "Tyson Foods Inc."),
    ("@BANKS_167879", "Dean Banks", "Tyson Foods Inc."),
    ("@LAMACH_51668", "Michael Lamach", "Trane Technologies PLC"),
    ("@REGNERY_172500", "David Regnery", "Trane Technologies PLC"),
    ("@ZELNICK_51001", "Strauss Zelnick", "Take-Two Interactive Software Inc."),
    ("@DORSEY_61271", "Jack Dorsey", "Twitter Inc."),
    ("@TEMPLETON_50535", "Richard Templeton", "Texas Instruments Inc."),
    ("@CRUTCHER_77025", "Brian Crutcher", "Texas Instruments Inc."),
    ("@TEMPLETON_50535", "Richard Templeton", "Texas Instruments Inc."),
    ("@DONNELLY_50436", "Scott Donnelly", "Textron Inc."),
    ("@MARR_51029", "John Marr", "Tyler Technologies Inc."),
    ("@MOORE_51034", "Lyne Moore", "Tyler Technologies Inc."),
    ("@PLANK_51076", "Kevin Plank", "Under Armour Inc."),
    ("@FRISK_171315", "Patrik Frisk", "Under Armour Inc."),
    ("@MUNOZ_68636", "Oscar Munoz", "United Continental Holdings Inc."),
    ("@MUNOZ_68636", "Oscar Munoz", "United Airlines Holdings Inc."),
    ("@MUNOZ_68636", "Oscar Munoz", "United Continental Holdings Inc."),
    ("@MUNOZ_68636", "Oscar Munoz", "United Airlines Holdings Inc."),
    ("@KIRBY_91052", "Scott Kirby", "United Airlines Holdings Inc."),
    ("@TOOMEY_51065", "Thomas Toomey", "UDR Inc."),
    ("@MILLER_51092", "Alan Miller", "Universal Health Services Inc."),
    ("@MILLER_62735", "Marc Miller", "Universal Health Services Inc."),
    ("@DILLON_51133", "Mary Dillon", "Ulta Beauty Inc."),
    ("@KIMBELL_79358", "David Kimbell", "Ulta Beauty Inc."),
    ("@HEMSLEY_50706", "Stephen Hemsley", "UnitedHealth Group Inc."),
    ("@RENFRO_77077", "Larry Renfro", "UnitedHealth Group Inc."),
    ("@NELSON_172382", "Steven Nelson", "UnitedHealth Group Inc."),
    ("@WICHMANN_50707", "David Wichmann", "UnitedHealth Group Inc."),
    ("@WITTY_90336", "Andrew Witty", "UnitedHealth Group Inc."),
    ("@FRITZ_70478", "Lance Fritz", "Union Pacific Corp."),
    ("@ABNEY_58345", "David Abney", "United Parcel Service Inc."),
    ("@TOME_50139", "Carol Tome", "United Parcel Service Inc."),
    ("@KNEELAND_51130", "Michael Kneeland", "United Rentals Inc."),
    ("@FLANNERY_77462", "Matthew Flannery", "United Rentals Inc."),
    ("@DAVIS_50662", "Richard Davis", "U.S. Bancorp"),
    ("@CECERE_50664", "Andrew Cecere", "U.S. Bancorp"),
    ("@KELLY_61838", "Alfred Kelly", "Visa Inc."),
    ("@RENDLE_75483", "Steven Rendle", "VF Corp."),
    ("@MOONVES_51477", "Leslie Moonves", "CBS Corp."),
    ("@IANNIELLO_51479", "Joseph Ianniello", "ViacomCBS Inc."),
    ("@IANNIELLO_51479", "Joseph Ianniello", "ViacomCBS Inc."),
    ("@BAKISH_76790", "Robert Bakish", "ViacomCBS Inc."),
    ("@GORDER_57059", "Joseph Gorder", "Valero Energy Corp."),
    ("@HILL_58519", "Thomas Hill", "Vulcan Materials Co."),
    ("@ROTH_50709", "Steven Roth", "Vornado Realty Trust"),
    ("@STEPHENSON_51096", "Scott Stephenson", "Verisk Analytics Inc."),
    ("@BIDZOS_50666", "James Bidzos", "Verisign Inc."),
    ("@LEIDEN_51104", "Jeffrey Leiden", "Vertex Pharmaceuticals Inc."),
    ("@KEWALRAMANI_185235", "Reshma Kewalramani", "Vertex Pharmaceuticals Inc."),
    ("@CAFARO_50629", "Debra Cafaro", "Ventas Inc."),
    ("@BULGARELLI_177241", "Peter Bulgarelli", "Ventas Inc."),
    ("@LILLIBRIDGE_77371", "Todd Lillibridge", "Ventas Inc."),
    ("@MCADAM_50688", "Lowell McAdam", "Verizon Communications Inc."),
    ("@VESTBERG_170730", "Hans Vestberg", "Verizon Communications Inc."),
    ("@GOWRAPPAN_177261", "K. Gowrappan", "Verizon Communications Inc."),
    ("@DUNNE_177237", "Ronan Dunne", "Verizon Communications Inc."),
    ("@ERWIN_183794", "Tami Erwin", "Verizon Communications Inc."),
    ("@BETLER_58212", "Raymond Betler", "Westinghouse Air Brake Technologies Corp."),
    ("@MEASSON_90028", "Stephane Rambaud-Measson", "Westinghouse Air Brake Technologies Corp."),
    ("@SANTANA_184461", "Rafael Santana", "Westinghouse Air Brake Technologies Corp."),
    ("@OCONNELL_75494", "Christopher OConnell", "Waters Corp."),
    ("@BATRA_132675", "Udit Batra", "Waters Corp."),
    ("@PESSINA_60212", "Stefano Pessina", "Walgreens Boots Alliance Inc."),
    ("@MILLIGAN_50649", "Stephen Milligan", "Western Digital Corp."),
    ("@GOECKELER_174455", "David Goeckeler", "Western Digital Corp."),
    ("@LEVERETT_77232", "Allen Leverett", "WEC Energy Group Inc."),
    ("@KLAPPA_50677", "Gale Klappa", "WEC Energy Group Inc."),
    ("@KLAPPA_50677", "Gale Klappa", "WEC Energy Group Inc."),
    ("@FLETCHER_89875", "J. Fletcher", "WEC Energy Group Inc."),
    ("@DEROSA_58068", "Thomas DeRosa", "Welltower Inc."),
    ("@MITRA_171104", "Shankh Mitra", "Welltower Inc."),
    ("@SLOAN_50640", "Timothy Sloan", "Wells Fargo & Co."),
    ("@SCHARF_50701", "Charles Scharf", "Wells Fargo & Co."),
    ("@FETTIG_50596", "Jeff Fettig", "Whirlpool Corp."),
    ("@BITZER_77306", "Marc Bitzer", "Whirlpool Corp."),
    ("@HALEY_51088", "John Haley", "Willis Towers Watson PLC"),
    ("@FISH_50661", "James Fish", "Waste Management Inc."),
    ("@ARMSTRONG_50667", "Alan Armstrong", "The Williams Co. Inc."),
    ("@CHEESEWRIGHT_56840", "David Cheesewright", "Walmart Inc."),
    ("@MCMILLON_56810", "Douglas McMillon", "Walmart Inc."),
    ("@FORAN_58692", "Gregory Foran", "Walmart Inc."),
    ("@LORE_91015", "Marc Lore", "Walmart Inc."),
    ("@FURNER_94514", "John Furner", "Walmart Inc."),
    ("@MCKENNA_178512", "Judith McKenna", "Walmart Inc."),
    ("@FURNER_94514", "John Furner", "Walmart Inc."),
    ("@MCLAY_185566", "Kathryn McLay", "Walmart Inc."),
    ("@ASHE_66597", "Neil Ashe", "Walmart Inc."),
    ("@BERKLEY_69377", "Willliam Berkley", "W. R. Berkley Corp."),
    ("@VOORHEES_55769", "Steven Voorhees", "WestRock Co."),
    ("@VOORHEES_55769", "Steven Voorhees", "WestRock Co."),
    ("@GREEN_74924", "Eric Green", "West Pharmaceutical Services Inc."),
    ("@ERSEK_50656", "Hikmet Ersek", "The Western Union Co."),
    ("@SIMONS_56593", "Doyle Simons", "Weyerhaeuser Co."),
    ("@STOCKFISH_177356", "Devin Stockfish", "Weyerhaeuser Co."),
    ("@WYNN_50633", "Stephen Wynn", "Wynn Resorts Ltd."),
    ("@MADDOX_50636", "Matthew Maddox", "Wynn Resorts Ltd."),
    ("@FOWKE_50620", "Benjamin Fowke", "Xcel Energy Inc."),
    ("@FRENZEL_87247", "Robert Frenzel", "Xcel Energy Inc."),
    ("@GAVRIELOV_50631", "Moshe Gavrielov", "Xilinx Inc."),
    ("@PENG_77507", "Victor Peng", "Xilinx Inc."),
    ("@WOODS_57216", "Darren Woods", "Exxon Mobil Corp."),
    ("@SLOVIN_51559", "Jeffrey Slovin", "DENTSPLY Sirona Inc."),
    ("@CASEY_77119", "Donald Casey", "DENTSPLY Sirona Inc."),
    ("@DECKER_52712", "Patrick Decker", "Xylem Inc."),
    ("@CREED_58156", "Greg Creed", "Yum! Brands Inc."),
    ("@EATON_61179", "Roger Eaton", "Yum! Brands Inc."),
    ("@GIBBS_86239", "David Gibbs", "Yum! Brands Inc."),
    ("@FLORIN_75500", "Daniel Florin", "Zimmer Biomet Holdings Inc."),
    ("@HANSON_77640", "Bryan Hanson", "Zimmer Biomet Holdings Inc."),
    ("@GUSTAFSSON_50800", "Anders Gustafsson", "Zebra Technologies Corp."),
    ("@SIMMONS_50635", "Harris Simmons", "Zions Bancorporation National Association"),
    ("@BLACKFORD_68593", "David Blackford", "Zions Bancorporation National Association"),
    ("@ANDERSON_65636", "Aldon Anderson", "Zions Bancorporation National Association"),
    ("@ALAIX_56494", "Juan Alaix", "Zoetis Inc."),
    ("@PECK_77543", "Kristin Peck", "Zoetis Inc."),
]
